patterns:
  - "AKIA[0-9A-Z]{16}"  # AWS Access Key
  - "xox[baprs]-[0-9]{12}-[0-9]{12}-[0-9A-Za-z]{24}"  # Slack Token
  - "(?i)api[-_]?key['\"]?\\s*[:=]\\s*['\"]?([A-Za-z0-9_\\-]{20,50})['\"]?"  # Generic API Key
  - "(?i)password\\s*=\\s*['\"]\\w+"  # Generic passwords
  - "-----BEGIN RSA PRIVATE KEY-----" # RSA Private keys
entropy_threshold: 4.5  # Adjust entropy sensitivity (higher = stricter)